# espanso match file
# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# yaml-language-server: $schema=https://raw.githubusercontent.com/espanso/espanso/dev/schemas/match.schema.json

matches:
  # --- Simple text replacement ---
  # - trigger: ":espanso"
  #   replace: "Hi there!"

  # - trigger: ":txt"
  #   replace: "REPLY TO ME IN TEXT, DO NOT GENERATE AN IMAGE"

  # # --- Dates & Shell ---
  # - trigger: ":date"
  #   replace: "{{mydate}}"
  #   vars:
  #     - name: mydate
  #       type: date
  #       params:
  #         format: "%m/%d/%Y"

  # - trigger: ":shell"
  #   replace: "{{output}}"
  #   vars:
  #     - name: output
  #       type: shell
  #       params:
  #         cmd: "echo 'Hello from your shell'"


  - trigger: ":rpgcomic"
    replace: "Artstyle: High-fantasy digital illustration in a modern watercolor and ink aesthetic. The scene features clean, thin ink outlines combined with soft, textured digital watercolor washes. Character proportions follow a modern anime/manga influence."

  - trigger: ":marvel"
    replace: "Artstyle: Modern American comic book illustration, Marvel comics aesthetic. Clean and crisp black ink outlines, no cross-hatching. Smooth digital coloring with soft gradients and high color saturation. Dramatic studio lighting, isolated on a solid neutral white background."
  - trigger: ":vox"
    replace: "Artstyle: The artistic style features clean, Cellshaded, cel-shaded anime style, flat colors, bold outlines, simple shading, limited color palette, style of Vox Machina, style of Avatar The Last Airbender."
 
  # --- Iron Lotus ---
  - trigger: ":goral"
    replace: "A muscular orc character with glowing purple eyes intricate ( reference gface.jpg gbody.png ) "
  - trigger: ":kae" 
    replace: "a beautiful 18 year old asian platinum-silver haired woman  ( reference: kbody.png kface.png ) "
  - trigger: ":krix"
    replace: "A small, blue-skinned goblin wearing a leather aviator cap with goggles. ( reference: kxbody.jpeg kxface.jpeg ) "
  - trigger: ":factory"
    replace: "factory ( reference: factory.png) "
  - trigger: ":vault"
    replace: "vault ( reference: vault.png ) "
  - trigger: ":office"
    replace: "office  ( reference: office.png )  "
  - trigger: ":axe"
    replace: "office  ( reference: office.png )  "
  - trigger: ":hammer"
    replace: "office  ( reference: office.png )  " 

